### PR TITLE
Update glyphicons for bootstrap 3.3.2

### PR DESCRIPTION
**Pull request by gllmhyt**

### CODE REVIEW

**Comment by Psycojoker** [comment]
Thx <3

**Comment by gllmhyt** [comment]
You're welcome! :)

**Comment by Psycojoker** [comment]
@postblue hum, I don't know how and why but one of your PR seems to have broken the "VPN" writing :/ https://neutrinet.be/#vpn

**Comment by gllmhyt** [comment]
I have this:

How should it be written?

**Comment by Psycojoker** [comment]
Actually it's working fine on my other browsers, I don't know from where it's coming (I've emptied my cache several time), so let's say it's my fault them. Sorry for the bad report /o\

**Pull request merged**
